### ISSUE TITLE
Include detailed break-down of annotated and unannotated sections in texts

### ISSUE THREAD

**Issue by mlj** [proiel/proiel-treebank#11]
We should include a break-down of which parts of texts have been annotated and which remain to be annotated. It's probably a good idea to keep a (shorter?) version of this on the treebank webpage too, and make it easy to find from [Syntacticus](http://syntacticus.org).

See also #6, #7, #8, #9 and #10.

**Comment by jonathanrobie** [comment]
Thanks, this would be helpful.  I had been under the impression that the complete analysis was available, and a clear notice about what is missing would satisfy my needs.  I'll also be very happy when it is completed, of course.

**Comment by mlj** [comment]
@daghaug, would you like to have a go at this?
